//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ktp_Otamasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kitaplar
    {
        public int id { get; set; }
        public Nullable<int> kategoriID { get; set; }
        public string kitapAd { get; set; }
        public string yazar { get; set; }
        public string sayfaSayisi { get; set; }
        public Nullable<bool> aktiflik { get; set; }
    
        public virtual Kategoriler Kategoriler { get; set; }
    }
}
